# Generated by Django 3.2.6 on 2021-10-19 14:01

from django.db import migrations, models
import django.utils.timezone
import royal.models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0002_auto_20211018_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='agencia',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='comissao',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contaBancaria',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ctps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dataAdmissao',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='dataDemissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dataNascimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='descansoSemanal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='desconto',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fimAlmoco',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horaSaida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='inicioAlmoco',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numeroBanco',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoContaBancaria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ajusteestoque',
            name='itensArr',
            field=models.JSONField(blank=True, default=royal.models.listaProdutos, null=True),
        ),
        migrations.AlterField(
            model_name='ajusteestoque',
            name='parcelasArr',
            field=models.JSONField(blank=True, default=royal.models.parcelas, null=True),
        ),
        migrations.AlterField(
            model_name='contapagarreceber',
            name='parcelas',
            field=models.JSONField(default=royal.models.parcelas, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.JSONField(default=royal.models.endereco, null=True),
        ),
        migrations.AlterField(
            model_name='gerencianet',
            name='historico',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='grupoComb',
            field=models.JSONField(default=royal.models.grupoComb, null=True),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='tributacao',
            field=models.JSONField(default=royal.models.tributacao, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentos',
            name='endereco',
            field=models.JSONField(default=royal.models.endereco, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentos',
            name='itens',
            field=models.JSONField(default=royal.models.listaProdutos, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentos',
            name='parcelas',
            field=models.JSONField(default=royal.models.parcelas, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='atributosArray',
            field=models.JSONField(default=royal.models.atributos, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='composicoesArray',
            field=models.JSONField(default=royal.models.composicoes, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedoresArray',
            field=models.JSONField(default=royal.models.fornecedores, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='grupoComb',
            field=models.JSONField(default=royal.models.grupoComb, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='infoFiscais',
            field=models.JSONField(default=royal.models.infoFiscais, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tributacao',
            field=models.JSONField(default=royal.models.tributacao, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valCustos',
            field=models.JSONField(default=royal.models.valCustos, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=123, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default=123, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='vendapdv',
            name='listaProdutos',
            field=models.JSONField(default=royal.models.listaProdutos, null=True),
        ),
    ]
