# Generated by Django 3.2.6 on 2021-10-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0004_alter_usuario_dataadmissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='diasTrabalhados',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
