# Generated by Django 3.2.6 on 2021-10-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0007_auto_20211020_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendapdv',
            name='dataPagamento',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='vendapdv',
            name='dataRegistro',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
