# Generated by Django 3.2.6 on 2021-10-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0008_auto_20211020_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categorias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
