# Generated by Django 3.2.6 on 2021-10-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0009_usuario_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dataNascimento',
            field=models.CharField(max_length=12),
        ),
    ]
