# Generated by Django 3.2.6 on 2021-10-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0010_alter_usuario_datanascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaspdv',
            name='historico',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
