# Generated by Django 3.2.6 on 2021-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0011_caixaspdv_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendapdv',
            name='dataPagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendapdv',
            name='dataRegistro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
