# Generated by Django 3.2.6 on 2021-10-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0012_auto_20211020_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentos',
            name='dataConfirmacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
