# Generated by Django 3.2.6 on 2021-10-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0014_auto_20211020_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusteestoque',
            name='dataConfirmacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ajusteestoque',
            name='dataCriacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ajusteestoque',
            name='dataVencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
