# Generated by Django 3.2.6 on 2021-10-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0015_auto_20211020_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagarreceber',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
