# Generated by Django 3.2.6 on 2021-10-21 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0016_alter_contapagarreceber_vencimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=18)),
                ('razaoSocial', models.CharField(max_length=38)),
                ('ativo', models.PositiveIntegerField()),
                ('nomeFantasia', models.CharField(max_length=32)),
                ('apelido', models.CharField(blank=True, max_length=32, null=True)),
                ('suframa', models.CharField(blank=True, max_length=18, null=True)),
                ('dataFundacao', models.DateField(null=True)),
                ('inscricaoEstadual', models.CharField(blank=True, max_length=15, null=True)),
                ('inscricaoMunicipal', models.CharField(blank=True, max_length=15, null=True)),
                ('isentoIe', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
