# Generated by Django 3.2.6 on 2021-10-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0017_configuracoessistema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracoessistema',
            old_name='ativo',
            new_name='status',
        ),
    ]
