# Generated by Django 3.2.6 on 2021-10-21 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0020_alter_configuracoessistema_icones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoessistema',
            name='icones',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='royal.configicones'),
            preserve_default=False,
        ),
    ]
