# Generated by Django 3.2.6 on 2021-10-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0022_alter_configuracoessistema_icones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracoessistema',
            old_name='configuracaoBandeira',
            new_name='configuracaoBandeiraArr',
        ),
    ]
