# Generated by Django 3.2.6 on 2021-10-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0016_auto_20211021_1518'),
        ('royal', '0023_rename_configuracaobandeira_configuracoessistema_configuracaobandeiraarr'),
    ]

    operations = [
    ]
