# Generated by Django 3.2.6 on 2021-10-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0024_merge_20211021_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajusteestoque',
            old_name='parcelasArr',
            new_name='parcelas',
        ),
    ]
