# Generated by Django 3.2.6 on 2021-10-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0025_rename_parcelasarr_ajusteestoque_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendido',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
