# Generated by Django 3.2.6 on 2021-10-26 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0029_alter_vendapdv_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendapdv',
            name='caixa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caixas', to='royal.caixaspdv'),
        ),
    ]
