# Generated by Django 3.2.6 on 2021-10-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0030_alter_vendapdv_caixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendapdv',
            name='produtos',
        ),
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royal.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royal.vendapdv')),
            ],
        ),
    ]
