# Generated by Django 3.2.6 on 2021-10-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0032_auto_20211028_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contapagarreceber',
            old_name='codIdentificador',
            new_name='nDocumento',
        ),
    ]
