# Generated by Django 3.2.6 on 2021-10-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0033_rename_codidentificador_contapagarreceber_ndocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagarreceber',
            name='nDocumento',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
