# Generated by Django 3.2.6 on 2021-11-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0034_alter_contapagarreceber_ndocumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapagarreceber',
            name='categorias',
        ),
        migrations.AlterField(
            model_name='contapagarreceber',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='royal.categoriaconta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
