# Generated by Django 3.2.6 on 2021-11-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0035_auto_20211103_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveBigIntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royal.produto')),
            ],
        ),
        migrations.AddField(
            model_name='ajusteestoque',
            name='produtos',
            field=models.ManyToManyField(to='royal.MovimentacaoProduto'),
        ),
    ]
