# Generated by Django 3.2.6 on 2021-11-03 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0036_auto_20211103_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajusteestoque',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoproduto',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='ajusteestoque',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 3, 13, 33, 2, 547845, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajusteestoque',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 3, 13, 33, 4, 553527, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
