# Generated by Django 3.2.6 on 2021-11-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0037_auto_20211103_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoproduto',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
