# Generated by Django 3.2.6 on 2021-11-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0038_alter_movimentacaoproduto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='tipo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
