# Generated by Django 3.2.6 on 2021-11-03 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0040_movimentacaoproduto_itensarr'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='clienteFornecedor',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='cpfCnpj',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='dataConfirmacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='dataCriacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='dataVencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='formaPagamento',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='numero',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='outrasDespesas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='parcelas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='quantidadeParcelas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='situacao',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='totalAjusteGeral',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='totalItens',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='valorFrete',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='valorPago',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='valorParcela',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoproduto',
            name='valorRecebido',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoproduto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
