# Generated by Django 3.2.6 on 2021-11-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0041_auto_20211103_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciaNetBolix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64)),
                ('pix', models.JSONField()),
                ('link', models.URLField()),
                ('pdf', models.JSONField()),
                ('expire_at', models.DateField()),
                ('charge_id', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=12)),
                ('total', models.PositiveIntegerField()),
                ('payment', models.CharField(max_length=24)),
            ],
        ),
    ]
