# Generated by Django 3.2.6 on 2021-11-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0042_gerencianetbolix'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerencianetbolix',
            name='cliente',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gerencianetbolix',
            name='expire_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gerencianetbolix',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gerencianetbolix',
            name='payment',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='gerencianetbolix',
            name='pdf',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gerencianetbolix',
            name='pix',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gerencianetbolix',
            name='status',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='gerencianetbolix',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
