# Generated by Django 3.2.6 on 2021-11-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0043_auto_20211109_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciaNetCarnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet_id', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, max_length=12, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('pdf', models.JSONField(blank=True, null=True)),
                ('charges', models.JSONField(blank=True, null=True)),
                ('cliente', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
