# Generated by Django 3.2.6 on 2021-11-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0044_gerencianetcarnes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerencianetcarnes',
            name='cover',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
