# Generated by Django 3.2.6 on 2021-11-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0045_gerencianetcarnes_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerencianetbolix',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gerencianetcarnes',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='bolix',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='royal.gerencianetbolix'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='carne',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='royal.gerencianetcarnes'),
            preserve_default=False,
        ),
    ]
