# Generated by Django 3.2.6 on 2021-11-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0046_auto_20211111_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentos',
            name='bolix',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='royal.gerencianetbolix'),
        ),
        migrations.AlterField(
            model_name='orcamentos',
            name='carne',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='royal.gerencianetcarnes'),
        ),
    ]
