# Generated by Django 3.2.6 on 2021-11-12 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0047_auto_20211111_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentos',
            name='bolix',
        ),
        migrations.RemoveField(
            model_name='orcamentos',
            name='carne',
        ),
        migrations.AddField(
            model_name='gerencianetbolix',
            name='orcamento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='royal.orcamentos'),
        ),
    ]
