# Generated by Django 3.2.6 on 2021-11-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0048_auto_20211112_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerencianetbolix',
            name='orcamento',
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='bolix',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='royal.gerencianetbolix'),
        ),
    ]
