# Generated by Django 3.2.6 on 2021-11-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0051_orcamentos_carne'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteestoque',
            name='bolix',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='royal.gerencianetbolix'),
        ),
        migrations.AddField(
            model_name='ajusteestoque',
            name='carne',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='royal.gerencianetcarnes'),
        ),
    ]
